# Default config file. To overwrite these configs, make a new file named `config.yml`
# in the same directory as `config-default.yml`, `config.yml` will override any values set
# in `config-default.yml` when the program runs. If not mentioned in `config.yml`,
# `config-default.yml` will serve as the default value for the variable.

# !ENV - Takes variable from enviroment variables.
# !JOIN - Join fellow config variables together. https://bit.ly/3qakxSR

# If you add a new default config variable. 
# Be sure you add it to constants.py Dataclasses as well.

bot:
    prefix:     !ENV    "BOT_PREFIX"
    token:      !ENV    "BOT_TOKEN"
    log_level:  !ENV    "LOG_LEVEL" # NOTSET | TRACE | DEBUG | INFO | WARN | ERROR | CRITICAL
    database:           "DATABASE.db"

style:
    colours:
        soft_red:     0xcd6d6d
        soft_green:   0x68c290
        soft_orange:  0xf9cb54
        bright_green: 0x01d277

    emojis:
        status_online:  "<:status_online:470326272351010816>"
        status_idle:    "<:status_idle:470326266625785866>"
        status_dnd:     "<:status_dnd:470326272082313216>"
        status_offline: "<:status_offline:470326266537705472>"

        incident_actioned:      "<:incident_actioned:719645530128646266>"
        incident_unactioned:    "<:incident_unactioned:719645583245180960>"
        incident_investigating: "<:incident_investigating:719645658671480924>"

        bullet:     "\u2022"
        pencil:     "\u270F"
        new:        "\U0001F195"
        cross_mark: "\u274C"
        check_mark: "\u2705"

    icons:
        crown_blurple: "https://cdn.discordapp.com/emojis/469964153289965568.png"
        crown_green:   "https://cdn.discordapp.com/emojis/469964154719961088.png"
        crown_red:     "https://cdn.discordapp.com/emojis/469964154879344640.png"

        defcon_denied:   "https://cdn.discordapp.com/emojis/472475292078964738.png"
        defcon_disabled: "https://cdn.discordapp.com/emojis/470326273952972810.png"
        defcon_enabled:  "https://cdn.discordapp.com/emojis/470326274213150730.png"
        defcon_updated:  "https://cdn.discordapp.com/emojis/472472638342561793.png"

        filtering: "https://cdn.discordapp.com/emojis/472472638594482195.png"

        hash_blurple: "https://cdn.discordapp.com/emojis/469950142942806017.png"
        hash_green:   "https://cdn.discordapp.com/emojis/469950144918585344.png"
        hash_red:     "https://cdn.discordapp.com/emojis/469950145413251072.png"

        message_bulk_delete: "https://cdn.discordapp.com/emojis/469952898994929668.png"
        message_delete:      "https://cdn.discordapp.com/emojis/472472641320648704.png"
        message_edit:        "https://cdn.discordapp.com/emojis/472472638976163870.png"

        sign_in:  "https://cdn.discordapp.com/emojis/469952898181234698.png"
        sign_out: "https://cdn.discordapp.com/emojis/469952898089091082.png"

        user_ban:    "https://cdn.discordapp.com/emojis/469952898026045441.png"
        user_unban:  "https://cdn.discordapp.com/emojis/469952898692808704.png"
        user_update: "https://cdn.discordapp.com/emojis/469952898684551168.png"

        user_mute:     "https://cdn.discordapp.com/emojis/472472640100106250.png"
        user_unmute:   "https://cdn.discordapp.com/emojis/472472639206719508.png"
        user_verified: "https://cdn.discordapp.com/emojis/470326274519334936.png"

        user_warn: "https://cdn.discordapp.com/emojis/470326274238447633.png"

        pencil: "https://cdn.discordapp.com/emojis/470326272401211415.png"

        remind_blurple: "https://cdn.discordapp.com/emojis/477907609215827968.png"
        remind_green:   "https://cdn.discordapp.com/emojis/477907607785570310.png"
        remind_red:     "https://cdn.discordapp.com/emojis/477907608057937930.png"

        questionmark: "https://cdn.discordapp.com/emojis/512367613339369475.png"

        voice_state_blue:  "https://cdn.discordapp.com/emojis/656899769662439456.png"
        voice_state_green: "https://cdn.discordapp.com/emojis/656899770094452754.png"
        voice_state_red:   "https://cdn.discordapp.com/emojis/656899769905709076.png"

guild:
    id:     622243127435984927
    invite: "https://discord.gg/piracy"

    categories:
        server:                         622243127435984928
        community:                      622248916888322058
        moderation:   &MOD_CATEGORY     624255126089236503
        development:                    787280267349983282
        logs:         &LOGS_CATEGORY    758178210642395137
        archive:                        708521071493644339

    channels:
        # server
        rules:                          623100638812962816
        announcements:                  624256442085539855

        # community
        general:                        631919775613845504
        shitposts:                      706852554062954628
        bots:                           650855150407254016
        art:                            796225669998444574

        # moderation
        reddit_posts: &REDDIT_CHANNEL   623809718011297792
        moderation:   &MOD_CHANNEL      624253391563915264
        commands:     &COMMAND_CHANNEL  787029607210680331
        votes:        &VOTE_CHANNEL     778724263929577513

        # development
        chiya_dev:                      798322374905692162
        bot_testing:                    787280381111173120
        chiya_todo:                     788062322500436009
        chiya_github:                   798372298607296583
        index_dev:                      798322401389445130
        index_editors:                  788082651469840436
        index_todo:                     785127927884152852
        index_github:                   798372253934682143
        wiki_github:                    798372362708844574

        # logs
        joins_leaves:                   781788303770255371

        # archive
        development:                    787031443011403797
        tools_guides:                   660973607132069958
        wallpapers:                     785755715494477834

    moderation_channels:
        - *REDDIT_CHANNEL
        - *MOD_CHANNEL
        - *COMMAND_CHANNEL
        - *VOTE_CHANNEL

    submission_channels:
        - *REDDIT_CHANNEL

    roles:
        # common roles.
        perverts:                           745670444606029915

        # staff roles.
        admin:          &ADMIN_ROLE         758145222017286205
        staff:          &STAFF_ROLE         763031634379276308
        discord_mod:    &DISCORD_MOD_ROLE   794473938373705758
        reddit_mod:     &REDDIT_MOD_ROLE    794681529145753612

        # special roles
        developer:      &DEVELOPER_ROLE     778474062619082753
        booster:                            660678752245645317
    
    staff_roles:
        - *ADMIN_ROLE
        - *STAFF_ROLE
        - *DISCORD_MOD_ROLE
        - *REDDIT_MOD_ROLE

reddit:
    subreddit:      !ENV    "REDDIT_SUBREDDIT"
    client_id:      !ENV    "REDDIT_CLIENT_ID"
    client_secret:  !ENV    "REDDIT_SECRET"
    reddit_posts:           *REDDIT_CHANNEL
    poll_rate:              3 # In seconds.
    user_agent:     !ENV    "REDDIT_USER_AGENT"

config:
    required_keys: ['bot.token']
